"""empty message

Revision ID: 054ab8ac5405
Revises: 4409735aaf19
Create Date: 2020-07-20 14:35:44.560701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054ab8ac5405'
down_revision = '4409735aaf19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('project_name', sa.String(length=32), nullable=False),
    sa.Column('project_desc', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name')
    )
    op.drop_table('prject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prject',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('create_time', sa.INTEGER(), nullable=True),
    sa.Column('update_time', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.SMALLINT(), nullable=True),
    sa.Column('project_name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('project_desc', sa.VARCHAR(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name')
    )
    op.drop_table('project')
    # ### end Alembic commands ###
