"""empty message

Revision ID: 55e89ff16828
Revises: 77138404a65c
Create Date: 2020-08-13 19:06:56.698758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e89ff16828'
down_revision = '77138404a65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic', sa.String(length=100), nullable=True, comment='截圖地址'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.drop_column('pic')

    # ### end Alembic commands ###
