"""empty message

Revision ID: 6d70d3be0630
Revises: 4260a7d2ee9d
Create Date: 2020-08-18 17:49:42.076444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d70d3be0630'
down_revision = '4260a7d2ee9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=True, comment='步骤名称'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
