"""empty message

Revision ID: 746376b818aa
Revises: 05f52e4eda1c
Create Date: 2020-07-16 17:55:24.468736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746376b818aa'
down_revision = '05f52e4eda1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tastTable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(length=32), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tastTable')
    # ### end Alembic commands ###
