"""empty message

Revision ID: 77138404a65c
Revises: 
Create Date: 2020-08-03 16:56:06.959026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77138404a65c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.drop_column('body')

    with op.batch_alter_table('uicase', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uicase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=200), nullable=True))

    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
