"""empty message

Revision ID: 954303d1a114
Revises: 55e89ff16828
Create Date: 2020-08-13 22:03:15.894942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954303d1a114'
down_revision = '55e89ff16828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.String(length=100), nullable=True, comment='验证数据'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###
