"""empty message

Revision ID: bbabd0feafd5
Revises: 30ac086478bb
Create Date: 2020-07-23 15:02:03.473738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbabd0feafd5'
down_revision = '30ac086478bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True, comment='测试报告'),
    sa.Column('result', sa.Boolean(), nullable=True, comment='测试结果'),
    sa.Column('count', sa.Integer(), nullable=True, comment='用例数'),
    sa.Column('success', sa.Integer(), nullable=True, comment='成功数'),
    sa.Column('html', sa.TEXT(), nullable=True, comment='报告html'),
    sa.Column('summary', sa.TEXT(), nullable=True, comment='报告详情'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('interfaces', sa.Column('tester', sa.String(length=32), nullable=True, comment='测试人'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interfaces', 'tester')
    op.drop_table('report')
    # ### end Alembic commands ###
