"""empty message

Revision ID: c16176a368f6
Revises: 
Create Date: 2020-07-24 16:58:09.191986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16176a368f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True, comment='做扩展'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='用例名称'),
    sa.Column('desc', sa.String(length=32), nullable=True, comment='desc'),
    sa.Column('request', sa.TEXT(), nullable=True, comment='测试数据'),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='用例項目'),
    sa.Column('interface_id', sa.INTEGER(), nullable=True, comment='用例的接口'),
    sa.Column('author', sa.String(length=32), nullable=True, comment='创建者'),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case')
    # ### end Alembic commands ###
