# NOTE: Generated By HttpRunner v3.1.3
# FROM: suite\tesInterfaces\tulingTest.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseTulingtest(HttpRunner):

    config = Config("tulingTest").base_url("www.caoyongqi.top")

    teststeps = [
        Step(
            RunRequest("图灵接口测试")
            .post("http://www.tuling123.com/openapi/api")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "info": "你叫什么",
                    "key": "8fe3b232710c4c0d87b761ed5301e7a4",
                    "userid": "123456",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.text", "我是棒棒哒图灵机器人")
            .assert_equal("body.code", 100000)
        ),
    ]


if __name__ == "__main__":
    TestCaseTulingtest().test_start()
